'use strict'

const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')

test('package.json advertises a webapp with icon and Handset font', () => {
  const pkg = require('../package.json')
  assert.ok(pkg.keywords.includes('signalk-webapp'))
  assert.ok(pkg.keywords.includes('signalk-node-server-plugin'))
  assert.equal(pkg.signalk.appIcon, 'icon.png')
  assert.equal(pkg.signalk.displayName, 'Control Panel')
  const pub = path.join(__dirname, '..', 'public')
  assert.equal(fs.existsSync(path.join(pub, 'icon.png')), true)
  assert.equal(fs.existsSync(path.join(pub, 'HandsetCond.ttf')), true)
  assert.equal(fs.existsSync(path.join(pub, 'index.html')), true)
  assert.equal(fs.existsSync(path.join(pub, 'app.js')), true)
  assert.equal(fs.existsSync(path.join(pub, 'style.css')), true)
})

test('webapp uses HandsetCond and follows display light/dark', () => {
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8')
  assert.match(css, /HandsetCond\.ttf/)
  assert.match(css, /font-family:\s*Handset/)
  assert.match(css, /prefers-color-scheme:\s*light/)
  assert.match(html, /prefers-color-scheme:\s*dark/)
  assert.match(html, /viewport-fit=cover/)
  assert.match(css, /safe-area-inset-top/)
})

test('switch keys are green on and transparent off; monitors are green/red', () => {
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  assert.match(css, /backdrop-filter:\s*var\(--key-blur\)/)
  assert.match(css, /\.key\.switch\.on[\s\S]*background:\s*var\(--glass-on\)/)
  assert.match(css, /\.key\.switch\.off[\s\S]*background:\s*var\(--glass-clear\)/)
  assert.match(css, /\.key\.monitor\.on[\s\S]*background:\s*var\(--glass-on\)/)
  assert.match(css, /\.key\.monitor\.off[\s\S]*background:\s*var\(--glass-off\)/)
})

test('keys use milk glass and a fixed label size on mobile and desktop', () => {
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8')
  assert.doesNotMatch(html, /glassPicker/)
  assert.match(css, /--glass-on:\s*rgba\(46, 214, 110, 0\.7\)/)
  assert.match(css, /\.key[\s\S]*font-size:\s*1\.55rem/)
  assert.doesNotMatch(css, /\.key[\s\S]*font-size:\s*clamp/)
})

test('key labels wrap at spaces, not mid-word', () => {
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  assert.match(css, /\.key \.label[\s\S]*word-break:\s*normal/)
  assert.match(css, /\.key \.label[\s\S]*overflow-wrap:\s*normal/)
  assert.match(css, /\.key \.label[\s\S]*hyphens:\s*none/)
  assert.doesNotMatch(css, /word-break:\s*break-(?:word|all)/)
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  assert.match(js, /function fitLabels/)
  assert.match(js, /white-space:nowrap/)
})

test('phone keys fill the screen width in two or three columns', () => {
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  assert.match(js, /function layoutKeys/)
  assert.match(js, /function isPhoneWidth/)
  assert.match(js, /w < 768/)
  assert.match(js, /var MIN_KEY = 72/)
  assert.match(js, /function availableDeckHeight/)
  assert.match(js, /main\.clientHeight/)
  assert.match(css, /@media \(max-width:\s*48rem\)/)
  assert.match(css, /overflow:\s*hidden/)
  assert.doesNotMatch(css, /aspect-ratio/)
})

test('webapp uses a device key and has no password login', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8')
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  assert.match(html, /devicePending/)
  assert.doesNotMatch(html, /loginForm/)
  assert.doesNotMatch(html, /autocomplete="username"/)
  assert.doesNotMatch(js, /PasswordCredential/)
  assert.doesNotMatch(js, /\/signalk\/v1\/auth\/login/)
  assert.match(js, /\/signalk\/v1\/access\/requests/)
})

test('device request is posted once, not from the status poll', () => {
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  assert.match(js, /function deviceRequestGone/)
  assert.match(js, /function stopDevicePoll/)
  assert.match(js, /function startHrefPoll/)
  assert.match(js, /function markPosted/)
  assert.match(js, /POSTED_KEY/)
  assert.match(js, /auth: false/)
  assert.match(js, /credentials: false/)
  assert.match(js, /already requested/)
  assert.match(js, /memoryClientId/)
  assert.doesNotMatch(js, /goneReplaced/)
  assert.match(js, /if \(authRequired && !isAuthorized\(\)\) startDeviceRequest\(\)/)
  assert.match(js, /function setApproved/)
  assert.match(js, /if \(postedOnce\) return/)
  assert.doesNotMatch(js, /hadToken && authRequired/)
  assert.match(js, /credentials: false/)
})

test('webapp is Zeus-safe and requests a Signal K device key', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8')
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  assert.match(html, /navico-store/)
  assert.match(html, /IE=11/)
  assert.match(js, /XMLHttpRequest/)
  assert.match(js, /\/signalk\/v1\/access\/requests/)
  assert.match(js, /permissions:\s*'readwrite'/)
  assert.match(js, /Authorization',\s*'Bearer /)
  assert.doesNotMatch(js, /\basync function\b/)
  assert.doesNotMatch(js, /\bfetch\s*\(/)
  assert.doesNotMatch(js, /=>/)
  assert.match(css, /min-height:\s*100vh/)
  assert.doesNotMatch(css, /aspect-ratio/)
  assert.doesNotMatch(css, /grid-template-columns/)
})

test('header shows Connected or No connection instead of technical errors', () => {
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8')
  assert.match(html, /id="statusLine"/)
  assert.match(css, /header[\s\S]*flex-direction:\s*row/)
  assert.match(js, /function setConnection/)
  assert.match(js, /'Connected'/)
  assert.match(js, /'No connection\.\.\.'/)
  assert.match(css, /\.meta\.connected/)
  assert.match(css, /\.meta\.offline/)
  assert.doesNotMatch(js, /setStatus\(/)
  assert.doesNotMatch(js, /Plugin not started/)
})

test('status poll updates keys in place so scroll is kept', () => {
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  assert.match(js, /function updateKeys/)
  assert.match(js, /paintedSig/)
  assert.match(js, /if \(sig === paintedSig && updateKeys\(\)\) return/)
})

test('slider keys are red and require a left-to-right slide', () => {
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8')
  const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8')
  assert.match(css, /\.key\.slider/)
  assert.match(css, /\.key\.slider[\s\S]*background:\s*var\(--glass-off\)/)
  assert.match(css, /\.slider-knob/)
  assert.match(css, /\.slider-knob[\s\S]*background:\s*var\(--slider-fill\)/)
  assert.match(css, /\.slider-fill/)
  assert.match(css, /--slider-fill:/)
  assert.match(js, /function isSliderKey/)
  assert.match(js, /function onSlideStart/)
  assert.match(js, /function setSliderPos/)
  assert.match(js, /slider-fill/)
  assert.match(js, /data-mode="slider"/)
  assert.match(js, /slide\.max \* 0\.85/)
  assert.match(js, /var SLIDER_H = 72/)
})

test('plugin source registers readonly status and write toggle', () => {
  const src = fs.readFileSync(path.join(__dirname, '..', 'plugin', 'index.js'), 'utf8')
  assert.match(src, /plugin\.signalKApiRoutes/)
  assert.match(src, /router\.get\('\/' \+ PLUGIN_ID \+ '\/status'/)
  assert.match(src, /router\.get\('\/' \+ PLUGIN_ID \+ '\/buttons\/:id\/:state'/)
  assert.match(src, /plugin\.registerWithRouter/)
  assert.match(src, /write\.put\('\/buttons\/:id'/)
})
